version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: weather-alarm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: weather_alarm
      MYSQL_USER: weather_user
      MYSQL_PASSWORD: weather123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
    driver: local
