spring:
  profiles:
    active: local

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    defaults:
      enabled: true

logging:
  level:
    com.weather.alarm: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:weather_alarm_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

weather:
  api:
    kma:
      base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      service-key: mk6sFdhibofY28J1%2FHLsmsBnFewM6OeycmHj0L3xPve89k6MlaIkpDyGWnjVAqnTCmnU26o6qKRMVu58vlSkzQ%3D%3D

geocoding:
  api:
    key: 72FBD6BD-16CB-3097-802D-5C52F0F66D1A

vworld:
  api:
    key: 72FBD6BD-16CB-3097-802D-5C52F0F66D1A

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://outside-weather-mysql-production:3306/${MYSQL_DATABASE:outside_weather}
    username: ${MYSQL_USER:weather_user}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false

vworld:
  api:
    key: ${VWORLD_API_KEY}

weather:
  api:
    kma:
      base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
      service-key: ${KMA_API_KEY}

logging:
  level:
    com.weather.alarm: INFO
    org.springframework.web: WARN